package com.abctreinamentos;
// Generated Sep 3, 2019 2:02:26 AM by Hibernate Tools 5.2.11.Final

/**
 * Cliente generated by hbm2java
 */
public class Cliente implements java.io.Serializable {

	private int cpf;
	private String nome;
	private String email;

	public Cliente() {
	}

	public Cliente(int cpf, String nome, String email) {
		this.cpf = cpf;
		this.nome = nome;
		this.email = email;
	}

	public int getCpf() {
		return this.cpf;
	}

	public void setCpf(int cpf) {
		this.cpf = cpf;
	}

	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}
	
	// ToString metodo
	@Override
	public String toString() 
	{
		return "Cliente [cpf=" + cpf + ", nome=" + nome + ", email=" + email + "]";
	}

}
