package com.abctreinamentos;
// Generated Sep 3, 2019 2:02:26 AM by Hibernate Tools 5.2.11.Final

/**
 * Curso generated by hbm2java
 */
public class Curso implements java.io.Serializable {

	private int idcurso;
	private String nome;
	private float valor;
	private String url;

	public Curso() {
	}

	public Curso(int idcurso, String nome, float valor, String url) {
		this.idcurso = idcurso;
		this.nome = nome;
		this.valor = valor;
		this.url = url;
	}

	public int getIdcurso() {
		return this.idcurso;
	}

	public void setIdcurso(int idcurso) {
		this.idcurso = idcurso;
	}

	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public float getValor() {
		return this.valor;
	}

	public void setValor(float valor) {
		this.valor = valor;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}
	
	// ToString metodo
	@Override
	public String toString() 
	{
		return "Curso [idcurso=" + idcurso + ", nome=" + nome + ", valor=" + valor + " url=" + url + "]";
	}

}
