package com.abctreinamentos;
// Generated Sep 3, 2019 2:02:26 AM by Hibernate Tools 5.2.11.Final

/**
 * Pagamento generated by hbm2java
 */
public class Pagamento implements java.io.Serializable {

	private PagamentoId id;
	private String datainscricao;

	public Pagamento() {
	}

	public Pagamento(PagamentoId id, String datainscricao) {
		this.id = id;
		this.datainscricao = datainscricao;
	}

	public PagamentoId getId() {
		return this.id;
	}

	public void setId(PagamentoId id) {
		this.id = id;
	}

	public String getDatainscricao() {
		return this.datainscricao;
	}

	public void setDatainscricao(String datainscricao) {
		this.datainscricao = datainscricao;
	}
	
	// ToString metodo
	@Override
	public String toString() 
	{
		return "Pagamento [cpf=" + id.getCpf() + ", idcurso=" + id.getIdcurso() + ", data_inscricao=" + datainscricao + "]";
	}

}
