package com.abctreinamentos;
// Generated Sep 3, 2019 2:02:26 AM by Hibernate Tools 5.2.11.Final

/**
 * PagamentoId generated by hbm2java
 */
public class PagamentoId implements java.io.Serializable {

	private int cpf;
	private int idcurso;

	public PagamentoId() {
	}

	public PagamentoId(int cpf, int idcurso) {
		this.cpf = cpf;
		this.idcurso = idcurso;
	}

	public int getCpf() {
		return this.cpf;
	}

	public void setCpf(int cpf) {
		this.cpf = cpf;
	}

	public int getIdcurso() {
		return this.idcurso;
	}

	public void setIdcurso(int idcurso) {
		this.idcurso = idcurso;
	}

}
